import StarIcon from '@mui/icons-material/Star';

let ProductsData = [
  {
    img: require("../images/product1.jpg"),
    imgs1: require("../images/imgSlides/product1s1.jpg"),
    imgs2: require("../images/imgSlides/product1s2.jpg"),
    imgs3: require("../images/imgSlides/product1s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 699,
    buy: "Buy now",
  },
  {
    img: require("../images/product8.jpg"),
    imgs1: require("../images/imgSlides/product8s1.jpg"),
    imgs2: require("../images/imgSlides/product8s2.jpg"),
    imgs3: require("../images/imgSlides/product8s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Sweater",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 499,
    buy: "Buy now",
  },
  {
    img: require("../images/product2.jpg"),
    imgs1: require("../images/imgSlides/product2s1.jpg"),
    imgs2: require("../images/imgSlides/product2s2.jpg"),
    imgs3: require("../images/imgSlides/product2s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 549,
    buy: "Buy now",
  },
  {
    img: require("../images/product5.jpg"),
    imgs1: require("../images/imgSlides/product5s1.jpg"),
    imgs2: require("../images/imgSlides/product5s2.jpg"),
    imgs3: require("../images/imgSlides/product5s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 449,
    buy: "Buy now",
  },
  {
    img: require("../images/product3.jpg"),
    imgs1: require("../images/imgSlides/product3s1.jpg"),
    imgs2: require("../images/imgSlides/product3s2.jpg"),
    imgs3: require("../images/imgSlides/product3s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 650,
    buy: "Buy now",
  },
  {
    img: require("../images/product10.jpg"),
    imgs1: require("../images/imgSlides/product10s1.jpg"),
    imgs2: require("../images/imgSlides/product10s2.jpg"),
    imgs3: require("../images/imgSlides/product10s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Saree",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 999,
    buy: "Buy now",
  },
  {
    img: require("../images/product4.jpg"),
    imgs1: require("../images/imgSlides/product4s1.jpg"),
    imgs2: require("../images/imgSlides/product4s2.jpg"),
    imgs3: require("../images/imgSlides/product4s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 589,
    buy: "Buy now",
  },
  {
    img: require("../images/product11.jpg"),
    imgs1: require("../images/imgSlides/product11s1.jpg"),
    imgs2: require("../images/imgSlides/product11s2.jpg"),
    imgs3: require("../images/imgSlides/product11s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 839,
    buy: "Buy now",
  },
  {
    img: require("../images/product9.jpg"),
    imgs1: require("../images/imgSlides/product9s1.jpg"),
    imgs2: require("../images/imgSlides/product9s2.jpg"),
    imgs3: require("../images/imgSlides/product9s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Saree",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1299,
    buy: "Buy now",
  },
  {
    img: require("../images/product12.jpg"),
    imgs1: require("../images/imgSlides/product12s1.jpg"),
    imgs2: require("../images/imgSlides/product12s2.jpg"),
    imgs3: require("../images/imgSlides/product12s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 579,
    buy: "Buy now",
  },
  {
    img: require("../images/product6.jpg"),
    imgs1: require("../images/imgSlides/product6s1.jpg"),
    imgs2: require("../images/imgSlides/product6s2.jpg"),
    imgs3: require("../images/imgSlides/product6s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 575,
    buy: "Buy now",
  },
  {
    img: require("../images/product13.jpg"),
    imgs1: require("../images/imgSlides/product13s1.jpg"),
    imgs2: require("../images/imgSlides/product13s2.jpg"),
    imgs3: require("../images/imgSlides/product13s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Lehnga",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1549,
    buy: "Buy now",
  },
  {
    img: require("../images/product7.jpg"),
    imgs1: require("../images/imgSlides/product7s1.jpg"),
    imgs2: require("../images/imgSlides/product7s2.jpg"),
    imgs3: require("../images/imgSlides/product7s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Sweater",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 899,
    buy: "Buy now",
  },
  {
    img: require("../images/product14.jpg"),
    imgs1: require("../images/imgSlides/product14s1.jpg"),
    imgs2: require("../images/imgSlides/product14s2.jpg"),
    imgs3: require("../images/imgSlides/product14s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Suit",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1149,
    buy: "Buy now",
  },
];

export { ProductsData };

let WebsiteInfo = [
  {
    img: require("../images/freeshipping.png"),
    heading: "Free Shipping",
  },
  {
    img: require("../images/order.png"),
    heading: "Online Order",
  },
  {
    img: require("../images/savemoney.png"),
    heading: "Save Money",
  },
  {
    img: require("../images/promotions.png"),
    heading: "Promotions",
  },
  {
    img: require("../images/sell.png"),
    heading: "Happy Sell",
  },
  {
    img: require("../images/support.png"),
    heading: "24/7 Support",
  },
]

export {WebsiteInfo};

let HomeGrid = [
  {
    img: require('../images/homegrid1.jpg'),
    heading: "Buy 1 get 1 free",
    para: 'The best classic dress is on sale',
    link: '/shop/all',
  },
  {
    img: require('../images/homegridclothes2.jpg'),
    heading: "Upcoming Seasons",
    para: 'All Shirts on sale',
    link: '/shop/men',
  },
  {
    img: require('../images/homegrid3.jpg'),
    heading: "Womens Dressess",
    para: '50% off on all dressess',
    link: '/shop/women',
  },
  {
    img: require('../images/homegrid4.jpg'),
    heading: "Mens Accessories",
    para: '70% off on all accessories',
    color: 'ghostwhite',
    link: '/shop/accessories',
  },
]

export {HomeGrid};
