import StarIcon from '@mui/icons-material/Star';

let ShopMensData = [
  {
    img: require("../images/mensshirt1.jpg"),
    imgs1: require("../images/ImgSlides/mensshirt1s1.jpg"),
    imgs2: require("../images/ImgSlides/mensshirt1s2.jpg"),
    imgs3: require("../images/ImgSlides/mensshirt1s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 440,
    buy: "Buy now",
  },
  {
    img: require("../images/menscoat1.jpg"),
    imgs1: require("../images/ImgSlides/menscoat1s1.jpg"),
    imgs2: require("../images/ImgSlides/menscoat1s2.jpg"),
    imgs3: require("../images/ImgSlides/menscoat1s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Blazer",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 799,
    buy: "Buy now",
  },
  {
    img: require("../images/menskurta1.jpg"),
    imgs1: require("../images/ImgSlides/menskurta1s1.jpg"),
    imgs2: require("../images/ImgSlides/menskurta1s2.jpg"),
    imgs3: require("../images/ImgSlides/menskurta1s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Kurta",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 599,
    buy: "Buy now",
  },
  {
    img: require("../images/men1.jpg"),
    imgs1: require("../images/ImgSlides/men1s1.jpg"),
    imgs2: require("../images/ImgSlides/men1s2.jpg"),
    imgs3: require("../images/ImgSlides/men1s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Sweater",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 849,
    buy: "Buy now",
  },
  {
    img: require("../images/menscoat2.jpg"),
    imgs1: require("../images/ImgSlides/menscoat2s1.jpg"),
    imgs2: require("../images/ImgSlides/menscoat2s2.jpg"),
    imgs3: require("../images/ImgSlides/menscoat2s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Coat",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 990,
    buy: "Buy now",
  },
  {
    img: require("../images/mensshirt2.jpg"),
    imgs1: require("../images/ImgSlides/mensshirt2s1.jpg"),
    imgs2: require("../images/ImgSlides/mensshirt2s2.jpg"),
    imgs3: require("../images/ImgSlides/mensshirt2s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 399,
    buy: "Buy now",
  },
  {
    img: require("../images/men2.jpg"),
    imgs1: require("../images/ImgSlides/men2s1.jpg"),
    imgs2: require("../images/ImgSlides/men2s2.jpg"),
    imgs3: require("../images/ImgSlides/men2s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Jacket",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 649,
    buy: "Buy now",
  },
  {
    img: require("../images/menskurta2.jpg"),
    imgs1: require("../images/ImgSlides/menskurta2s1.jpg"),
    imgs2: require("../images/ImgSlides/menskurta2s2.jpg"),
    imgs3: require("../images/ImgSlides/menskurta2s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Kurta",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 709,
    buy: "Buy now",
  },
  {
    img: require("../images/men3.jpg"),
    imgs1: require("../images/ImgSlides/men3s1.jpg"),
    imgs2: require("../images/ImgSlides/men3s2.jpg"),
    imgs3: require("../images/ImgSlides/men3s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Denim Jacket",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 819,
    buy: "Buy now",
  },
  {
    img: require("../images/mensshirt3.jpg"),
    imgs1: require("../images/ImgSlides/mensshirt3s1.jpg"),
    imgs2: require("../images/ImgSlides/mensshirt3s2.jpg"),
    imgs3: require("../images/ImgSlides/mensshirt3s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 459,
    buy: "Buy now",
  },
  {
    img: require("../images/menskurta3.jpg"),
    imgs1: require("../images/ImgSlides/menskurta3s1.jpg"),
    imgs2: require("../images/ImgSlides/menskurta3s2.jpg"),
    imgs3: require("../images/ImgSlides/menskurta3s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Kurta",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 739,
    buy: "Buy now",
  },
  {
    img: require("../images/men4.jpg"),
    imgs1: require("../images/ImgSlides/men4s1.jpg"),
    imgs2: require("../images/ImgSlides/men4s2.jpg"),
    imgs3: require("../images/ImgSlides/men4s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Jacket",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 889,
    buy: "Buy now",
  },
  {
    img: require("../images/mensshirt4.jpg"),
    imgs1: require("../images/ImgSlides/mensshirt4s1.jpg"),
    imgs2: require("../images/ImgSlides/mensshirt4s2.jpg"),
    imgs3: require("../images/ImgSlides/mensshirt4s3.jpg"),
    cart: "Add to Cart",
    name: "Mens T-Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 499,
    buy: "Buy now",
  },
  {
    img: require("../images/men5.jpg"),
    imgs1: require("../images/ImgSlides/men5s1.jpg"),
    imgs2: require("../images/ImgSlides/men5s2.jpg"),
    imgs3: require("../images/ImgSlides/men5s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Sweater",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 835,
    buy: "Buy now",
  },
  {
    img: require("../images/menskurta4.jpg"),
    imgs1: require("../images/ImgSlides/menskurta4s1.jpg"),
    imgs2: require("../images/ImgSlides/menskurta4s2.jpg"),
    imgs3: require("../images/ImgSlides/menskurta4s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Kurta",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1099,
    buy: "Buy now",
  },
  {
    img: require("../images/men8.jpg"),
    imgs1: require("../images/ImgSlides/men8s1.jpg"),
    imgs2: require("../images/ImgSlides/men8s2.jpg"),
    imgs3: require("../images/ImgSlides/men8s3.jpg"),
    cart: "Add to Cart",
    name: "Mens T-Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 550,
    buy: "Buy now",
  },
  {
    img: require("../images/mensshirt5.jpg"),
    imgs1: require("../images/ImgSlides/mensshirt5s1.jpg"),
    imgs2: require("../images/ImgSlides/mensshirt5s2.jpg"),
    imgs3: require("../images/ImgSlides/mensshirt5s3.jpg"),
    cart: "Add to Cart",
    name: "Mens T-Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 425,
    buy: "Buy now",
  },
  {
    img: require("../images/men7.jpg"),
    imgs1: require("../images/ImgSlides/men7s1.jpg"),
    imgs2: require("../images/ImgSlides/men7s2.jpg"),
    imgs3: require("../images/ImgSlides/men7s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Formal Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 545,
    buy: "Buy now",
  },
  {
    img: require("../images/mensshirt6.jpg"),
    imgs1: require("../images/ImgSlides/mensshirt6s1.jpg"),
    imgs2: require("../images/ImgSlides/mensshirt6s2.jpg"),
    imgs3: require("../images/ImgSlides/mensshirt6s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 629,
    buy: "Buy now",
  },
  {
    img: require("../images/men6.jpg"),
    imgs1: require("../images/ImgSlides/men6s1.jpg"),
    imgs2: require("../images/ImgSlides/men6s2.jpg"),
    imgs3: require("../images/ImgSlides/men6s3.jpg"),
    cart: "Add to Cart",
    name: "Mens T-Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 350,
    buy: "Buy now",
  },
  {
    img: require("../images/men9.jpg"),
    imgs1: require("../images/ImgSlides/men9s1.jpg"),
    imgs2: require("../images/ImgSlides/men9s2.jpg"),
    imgs3: require("../images/ImgSlides/men9s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 489,
    buy: "Buy now",
  },
  {
    img: require("../images/men12.jpg"),
    imgs1: require("../images/ImgSlides/men12s1.jpg"),
    imgs2: require("../images/ImgSlides/men12s2.jpg"),
    imgs3: require("../images/ImgSlides/men12s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Blazer",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1250,
    buy: "Buy now",
  },
  {
    img: require("../images/men10.jpg"),
    imgs1: require("../images/ImgSlides/men10s1.jpg"),
    imgs2: require("../images/ImgSlides/men10s2.jpg"),
    imgs3: require("../images/ImgSlides/men10s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shirt",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 478,
    buy: "Buy now",
  },
  {
    img: require("../images/men11.jpg"),
    imgs1: require("../images/ImgSlides/men11s1.jpg"),
    imgs2: require("../images/ImgSlides/men11s2.jpg"),
    imgs3: require("../images/ImgSlides/men11s3.jpg"),
    cart: "Add to Cart",
    name: "Mens Coat",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1045,
    buy: "Buy now",
  },
];

let ShopAccessoriesData = [
  {
    img: require("../images/shoes1.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 990,
    buy: "Buy now",
  },
  {
    img: require("../images/glasses1.jpg"),
    cart: "Add to Cart",
    name: "Mens Glasses",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 140,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes11.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 2990,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes2.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1500,
    buy: "Buy now",
  },
  {
    img: require("../images/watch1.jpg"),
    cart: "Add to Cart",
    name: "Mens Watch",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 390,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes12.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 3449,
    buy: "Buy now",
  },
  {
    img: require("../images/glasses2.jpg"),
    cart: "Add to Cart",
    name: "Mens Glasses",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 580,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes3.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1100,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes4.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 999,
    buy: "Buy now",
  },
  {
    img: require("../images/watch2.jpg"),
    cart: "Add to Cart",
    name: "Mens Watch",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 549,
    buy: "Buy now",
  },
  {
    img: require("../images/glasses3.jpg"),
    cart: "Add to Cart",
    name: "Mens Glasses",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 250,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes5.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 740,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes6.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 839,
    buy: "Buy now",
  },
  {
    img: require("../images/watch3.jpg"),
    cart: "Add to Cart",
    name: "Mens Watch",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 400,
    buy: "Buy now",
  },
  {
    img: require("../images/glasses4.jpg"),
    cart: "Add to Cart",
    name: "Mens Glasses",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 310,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes7.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1310,
    buy: "Buy now",
  },
  {
    img: require("../images/watch4.jpg"),
    cart: "Add to Cart",
    name: "Mens Watch",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 430,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes8.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 679,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes9.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 900,
    buy: "Buy now",
  },
  {
    img: require("../images/shoes10.jpg"),
    cart: "Add to Cart",
    name: "Mens Shoes",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1219,
    buy: "Buy now",
  },
];

let ShopWomensData = [
  {
    img: require("../images/women1.jpg"),
    imgs1: require("../images/ImgSlides/women1s1.jpg"),
    imgs2: require("../images/ImgSlides/women1s2.jpg"),
    imgs3: require("../images/ImgSlides/women1s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Lenhga",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 990,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress1.jpg"),
    imgs1: require("../images/ImgSlides/womensdress1s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress1s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress1s3.jpg"), 
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 680,
    buy: "Buy now",
  },
  {
    img: require("../images/women2.jpg"),
    imgs1: require("../images/ImgSlides/women2s1.jpg"),
    imgs2: require("../images/ImgSlides/women2s2.jpg"),
    imgs3: require("../images/ImgSlides/women2s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Kurta",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 840,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress2.jpg"),
    imgs1: require("../images/ImgSlides/womensdress2s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress2s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress2s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 599,
    buy: "Buy now",
  },
  {
    img: require("../images/women4.jpg"),
    imgs1: require("../images/ImgSlides/women4s1.jpg"),
    imgs2: require("../images/ImgSlides/women4s2.jpg"),
    imgs3: require("../images/ImgSlides/women4s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Kurta",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 900,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress3.jpg"),
    imgs1: require("../images/ImgSlides/womensdress3s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress3s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress3s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 745,
    buy: "Buy now",
  },
  {
    img: require("../images/women5.jpg"),
    imgs1: require("../images/ImgSlides/women5s1.jpg"),
    imgs2: require("../images/ImgSlides/women5s2.jpg"),
    imgs3: require("../images/ImgSlides/women5s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Saree",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1200,
    buy: "Buy now",
  },
  {
    img: require("../images/women3.jpg"),
    imgs1: require("../images/ImgSlides/women3s1.jpg"),
    imgs2: require("../images/ImgSlides/women3s2.jpg"),
    imgs3: require("../images/ImgSlides/women3s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Kurta",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 780,
    buy: "Buy now",
  },
  {
    img: require("../images/women6.jpg"),
    imgs1: require("../images/ImgSlides/women6s1.jpg"),
    imgs2: require("../images/ImgSlides/women6s2.jpg"),
    imgs3: require("../images/ImgSlides/women6s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Saree",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1100,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress4.jpg"),
    imgs1: require("../images/ImgSlides/womensdress4s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress4s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress4s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 890,
    buy: "Buy now",
  },
  {
    img: require("../images/women7.jpg"),
    imgs1: require("../images/ImgSlides/women7s1.jpg"),
    imgs2: require("../images/ImgSlides/women7s2.jpg"),
    imgs3: require("../images/ImgSlides/women7s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Saree",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 999,
    buy: "Buy now",
  },
  {
    img: require("../images/women15.jpg"),
    imgs1: require("../images/ImgSlides/women15s1.jpg"),
    imgs2: require("../images/ImgSlides/women15s2.jpg"),
    imgs3: require("../images/ImgSlides/women15s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Lehnga",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1590,
    buy: "Buy now",
  },
  {
    img: require("../images/women8.jpg"),
    imgs1: require("../images/ImgSlides/women8s1.jpg"),
    imgs2: require("../images/ImgSlides/women8s2.jpg"),
    imgs3: require("../images/ImgSlides/women8s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Saree",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1349,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress5.jpg"),
    imgs1: require("../images/ImgSlides/womensdress5s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress5s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress5s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 800,
    buy: "Buy now",
  },
  {
    img: require("../images/women9.jpg"),
    imgs1: require("../images/ImgSlides/women9s1.jpg"),
    imgs2: require("../images/ImgSlides/women9s2.jpg"),
    imgs3: require("../images/ImgSlides/women9s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 549,
    buy: "Buy now",
  },
  {
    img: require("../images/women14.jpg"),
    imgs1: require("../images/ImgSlides/women14s1.jpg"),
    imgs2: require("../images/ImgSlides/women14s2.jpg"),
    imgs3: require("../images/ImgSlides/women14s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Lehnga",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1090,
    buy: "Buy now",
  },
  {
    img: require("../images/women10.jpg"),
    imgs1: require("../images/ImgSlides/women10s1.jpg"),
    imgs2: require("../images/ImgSlides/women10s2.jpg"),
    imgs3: require("../images/ImgSlides/women10s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 950,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress6.jpg"),
    imgs1: require("../images/ImgSlides/womensdress6s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress6s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress6s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 660,
    buy: "Buy now",
  },
  {
    img: require("../images/women11.jpg"),
    imgs1: require("../images/ImgSlides/women11s1.jpg"),
    imgs2: require("../images/ImgSlides/women11s2.jpg"),
    imgs3: require("../images/ImgSlides/women11s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 599,
    buy: "Buy now",
  },
  {
    img: require("../images/women16.jpg"),
    imgs1: require("../images/ImgSlides/women16s1.jpg"),
    imgs2: require("../images/ImgSlides/women16s2.jpg"),
    imgs3: require("../images/ImgSlides/women16s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Lehnga",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1279,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress7.jpg"),
    imgs1: require("../images/ImgSlides/womensdress7s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress7s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress7s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 780,
    buy: "Buy now",
  },
  {
    img: require("../images/women12.jpg"),
    imgs1: require("../images/ImgSlides/women12s1.jpg"),
    imgs2: require("../images/ImgSlides/women12s2.jpg"),
    imgs3: require("../images/ImgSlides/women12s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Top",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 500,
    buy: "Buy now",
  },
  {
    img: require("../images/women13.jpg"),
    imgs1: require("../images/ImgSlides/women13s1.jpg"),
    imgs2: require("../images/ImgSlides/women13s2.jpg"),
    imgs3: require("../images/ImgSlides/women13s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Lehnga",
    rating: <><StarIcon/><StarIcon/><StarIcon/></>,
    price: 1489,
    buy: "Buy now",
  },
  {
    img: require("../images/womensdress8.jpg"),
    imgs1: require("../images/ImgSlides/womensdress8s1.jpg"),
    imgs2: require("../images/ImgSlides/womensdress8s2.jpg"),
    imgs3: require("../images/ImgSlides/womensdress8s3.jpg"),
    cart: "Add to Cart",
    name: "Womens Dress",
    rating: <><StarIcon/><StarIcon/><StarIcon/><StarIcon/></>,
    price: 969,
    buy: "Buy now",
  },
];

export { ShopMensData, ShopAccessoriesData, ShopWomensData };